image: node:12 # change to match your node version

cache:
  paths:
    - sports_video_tagging_player/node_modules/

before_script:
  - cd sports_video_tagging_player
  - rm -rf dist
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - ls -la dist
    - mv dist ../public
    - ls -la ../public
  artifacts:
    paths:
      - public
  only:
    - master
